name: learn_dart
description: Learn by doing, code challenges, quizzes, and projects fuel your dart journey.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  cloud_firestore: ^4.0.2
  firebase_storage: ^11.0.2
  firebase_messaging: ^14.5.0
  firebase_crashlytics: ^3.0.15
  firebase_performance: ^0.9.1+2
  firebase_analytics: ^10.3.0
  firebase_remote_config: ^4.2.2
  firebase_app_check: ^0.2.1+8

  # State Management
  provider: ^6.1.1

  # User Interface
  flutter_card_swiper: ^7.0.0
  card_swiper: ^3.0.1
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  fl_chart: ^0.66.1


  # Features and Functionality
  share_plus: ^7.1.0 #To implement share feature
  url_launcher: ^6.1.14 #To launch url
  profanity_filter: ^2.0.0 #To filter profane words
  date_time_format: ^2.0.1 #To format DateTime in readable format

  #editor
  dart_style: ^2.3.4
  syntax_highlight: ^0.3.0
  code_text_field: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
