name: learn_dart
description: "Learn by doing, code challenges, quizzes, and projects fuel your dart journey."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # User Interface
  flutter_card_swiper: ^7.0.0
  card_swiper: ^3.0.1
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_adaptive_scaffold: ^0.1.8

  # Features and Functionality
  share_plus: ^7.1.0 #To implement share feature
  url_launcher: ^6.1.14 #To launch url
  profanity_filter: ^2.0.0 #To filter profane words
  date_time_format: ^2.0.1 #To format DateTime in readable format
  flutter_markdown: ^0.6.20 #

  #editor
  dart_style: ^2.3.4
  syntax_highlight: ^0.3.0
  code_text_field: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/tutorials/
