name: learn_dart
description: "Learn by doing, code challenges, quizzes, and projects fuel your Dart journey."
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # User Interface
  flutter_adaptive_scaffold: ^0.1.8
  cupertino_icons: ^1.0.2
  appinio_swiper: ^2.1.0
  google_fonts: ^6.2.1
  animations: ^2.0.11

  # Features and Functionality
  syntax_highlight: ^0.4.0
  flutter_markdown: ^0.7.1
  flutter_turtle: ^0.4.2
  url_launcher: ^6.1.14
  share_plus: ^9.0.0
  dart_style: ^2.3.4
  code_text_field: ^1.1.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  sembast: ^3.7.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  msix: ^3.16.7

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/tutorials/

flutter_launcher_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#F1EAFF"
    theme_color: "#F1EAFF"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
