// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7WfLYXeNuoomdTpLwdSTz1VrIVIHtt4k',
    appId: '1:61208255675:web:85ea7ad9c5e9afa0d59d9e',
    messagingSenderId: '61208255675',
    projectId: 'learndart01',
    authDomain: 'learndart01.firebaseapp.com',
    storageBucket: 'learndart01.appspot.com',
    measurementId: 'G-RVH1TQ4R54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPpcxzXaR_32xhECvJGrnPMQOs_2DC-SY',
    appId: '1:61208255675:android:2ae0787e92b82592d59d9e',
    messagingSenderId: '61208255675',
    projectId: 'learndart01',
    storageBucket: 'learndart01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXB7erXBsTlFLXL5g8QPdCWebE1TG840U',
    appId: '1:61208255675:ios:ae364170328e1e33d59d9e',
    messagingSenderId: '61208255675',
    projectId: 'learndart01',
    storageBucket: 'learndart01.appspot.com',
    iosBundleId: 'com.learnapp.dart.app',
  );
}
